export const  initialMaterials = [
    {
      id: "q3lYEM",
      name: "Small Box",
      volume: 1.5,
      w: "16 3/8",
      d: "12 5/8",
      h: "12 5/8",
      count: 0,
      img: "img/small.jpg",
      history: {},
    },
    {
      id: "KX1q8A",
      name: "Medium Box",
      volume: 3.0,
      w: "18",
      d: "18",
      h: "16",
      count: 0,
      img: "img/medium.jpg",
      history: {},
    },
    {
      id: "AT9F5y",
      name: "Large Box",
      volume: 4.5,
      w: "18",
      d: "18",
      h: "24",
      count: 0,
      img: "img/large.jpg",
      history: {},
    },
    {
      id: "L2NPOm",
      name: "Mattress Bag",
      description: "For use on mattresses & box springs",
      count: 0,
      img: "img/matbags.jpg",
      history: {},
    },
    {
      id: "Zb53TO",
      name: "Wardrobe (Rent)",
      volume: 13,
      w: "24",
      d: "24",
      h: "40",

      count: 0,
      img: "img/wardrobe.jpg",
      history: {},
    },
    {
      id: "XjYPgM",
      name: "Wardrobe (Buy)",
      volume: 13,
      w: "24",
      d: "24",
      h: "40",

      count: 0,
      img: "img/wardrobe.jpg",
      history: {},
    },
    {
      id: "Aic8ie",
      name: "Laydown Wardrobe",
      volume: 13,
      w: "24",
      d: "24",
      h: "40",

      count: 0,
      img: "img/laydown.jpg",
      history: {},
    },
    {
      id: "fjCPOT",
      name: "Mirror Pack (Small)",
      volume: 13,
      w: "24",
      d: "24",
      h: "40",

      count: 0,
      img: "img/smirror.jpg",
      history: {},
    },
    {
      id: "UmttCz",
      name: "Mirror Pack (Large)",
      volume: 13,
      w: "24",
      d: "24",
      h: "40",

      count: 0,
      img: "img/lmirror.jpg",
      history: {},
    },
    {
      id: "dW96Oj",
      name: "Paper Pads",
      count: 0,
      img: "img/pads.jpg",
      history: {},
    },
    {
      id: "K6HCr1",
      name: "Stretch Wrap",
      count: 0,
      img: "img/wrap.jpg",
      history: {},
    },
    {
      id: "s1s12u",
      name: "Carpet Protection",
      count: 0,
      img: "img/carpet.jpg",
      history: {},
    },
    {
      id: "INaIjO",
      name: "Ropes",
      count: 0,
      img: "img/rope.jpg",
      history: {},
    },
    {
      id: "s0mSbR",
      name: "Blankets",
      count: 0,
      img: "img/blanket.jpg",
      history: {},
    },
  ];